# -*- coding: utf-8 -*-
"""yolo_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPHkIpi38DEWiYDI-ZRu35FcNrv8ipbT
"""

pip install ultralytics opencv-python numpy

import cv2
import numpy as np
from ultralytics import YOLO

# Load YOLOv8 model
model = YOLO("yolov8n.pt")  # Lightweight version for faster inference

# Path to input video
video_path = "/content/CatZoomies.mp4"
output_path = "CatZoomies_Detected.avi"

cap = cv2.VideoCapture(video_path)

# Get video properties
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))

# Define the codec and create VideoWriter object
video_writer = cv2.VideoWriter(
    output_path, cv2.VideoWriter_fourcc(*"MJPG"), fps, (frame_width, frame_height)
)

# Store previous positions for tracking line
cat_positions = []

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Perform object detection
    results = model(frame)

    for result in results:
        for box in result.boxes:
            class_id = int(box.cls[0])  # Get class ID
            class_name = model.names[class_id]  # Get class name

            # Detect only "cat"
            if class_name.lower() == "cat":
                x1, y1, x2, y2 = map(int, box.xyxy[0])  # Bounding box coordinates
                confidence = float(box.conf[0])  # Confidence score

                # Append center point for tracking
                center_x, center_y = (x1 + x2) // 2, (y1 + y2) // 2
                cat_positions.append((center_x, center_y))

                # Draw bounding box (blue color)
                cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 3)
                label = f"{class_name} {confidence:.2f}"
                cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

    # Draw tracking line
    for i in range(1, len(cat_positions)):
        cv2.line(frame, cat_positions[i - 1], cat_positions[i], (255, 0, 0), 2)

    # Add text at the top-right corner
    cv2.putText(frame, "Adunwit-Clicknext-Intern-2025", (frame.shape[1] - 400, 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)

    # Write the frame to the video file
    video_writer.write(frame)

# Release resources
cap.release()
video_writer.release()

print(f"Processed video saved at: {output_path}")

from google.colab import files
files.download("/content/CatZoomies_Detected.avi")